apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: zomato-deployx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: conta11
        image: sharmaatulkumar29/zomatoimage:695918829d21bbb63190e8716bcae7dffe243d98
        ports:
          - containerPort: 3000
