apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: zomato-deployx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: conta11
        image: sharmaatulkumar29/zomatoimage:8e03d1c5bdbb4be749ae611009ecb542cbdb8a16
        ports:
          - containerPort: 3000
