apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: zomato-deployx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: conta11
        image: sharmaatulkumar29/zomatoimage:32a1a94b7fd667c50b5869048e62e05c189a777e
        ports:
          - containerPort: 3000
